services: 
  component:
    # for building from source
    image: qanary-component-qb-python-kgqanwrapper:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - '8082:8082'
    env_file:
      - .env
    volumes:
      - ./KGQAn/data:/KGQAn/data
