name: Deploy Component

on:
  workflow_call:

jobs:
  init-update:
    runs-on: ubuntu-latest
    env:
      SPRING_BOOT_ADMIN_USER: ${{ secrets.SPRING_BOOT_ADMIN_USER }}
      SPRING_BOOT_ADMIN_PASSWORD: ${{ secrets.SPRING_BOOT_ADMIN_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare deployment
        run: bash -c ./service_config/prepare_deployment.sh
      - name: Init update
        uses: WSE-research/docker-service-updater@v0.2.1
        with:
          api_key: ${{ secrets.API_KEY }}
          updater_host: ${{ secrets.UPDATER_HOST }}
